version: '3'  
 
services: 

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto-data/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    
  panduza-platform:
    container_name: panduza-cxx-platform
    user: builder
    build:
      context: ../../../panduza-cxx-platform
    network_mode: host
    privileged: true
    volumes:
      - ../../../panduza-cxx-platform:/panduza-cxx-platform
      - ./panduza/tree.json:/etc/panduza/tree.json
      - ../../.:/home/builder/panduza-cxx-class-boundary-scan